// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.17.3
// source: services/abs/protobuf/abs.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Abs_List_FullMethodName   = "/go.micro.service.abs.Abs/List"
	Abs_Create_FullMethodName = "/go.micro.service.abs.Abs/Create"
	Abs_Get_FullMethodName    = "/go.micro.service.abs.Abs/Get"
	Abs_Update_FullMethodName = "/go.micro.service.abs.Abs/Update"
	Abs_Delete_FullMethodName = "/go.micro.service.abs.Abs/Delete"
)

// AbsClient is the client API for Abs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AbsClient interface {
	List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Response, error)
	Create(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Response, error)
	Get(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*Response, error)
}

type absClient struct {
	cc grpc.ClientConnInterface
}

func NewAbsClient(cc grpc.ClientConnInterface) AbsClient {
	return &absClient{cc}
}

func (c *absClient) List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Abs_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *absClient) Create(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Abs_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *absClient) Get(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Abs_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *absClient) Update(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Abs_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *absClient) Delete(ctx context.Context, in *EntityRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Abs_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AbsServer is the server API for Abs service.
// All implementations must embed UnimplementedAbsServer
// for forward compatibility
type AbsServer interface {
	List(context.Context, *emptypb.Empty) (*Response, error)
	Create(context.Context, *emptypb.Empty) (*Response, error)
	Get(context.Context, *EntityRequest) (*Response, error)
	Update(context.Context, *EntityRequest) (*Response, error)
	Delete(context.Context, *EntityRequest) (*Response, error)
	mustEmbedUnimplementedAbsServer()
}

// UnimplementedAbsServer must be embedded to have forward compatible implementations.
type UnimplementedAbsServer struct {
}

func (UnimplementedAbsServer) List(context.Context, *emptypb.Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedAbsServer) Create(context.Context, *emptypb.Empty) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAbsServer) Get(context.Context, *EntityRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAbsServer) Update(context.Context, *EntityRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAbsServer) Delete(context.Context, *EntityRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAbsServer) mustEmbedUnimplementedAbsServer() {}

// UnsafeAbsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AbsServer will
// result in compilation errors.
type UnsafeAbsServer interface {
	mustEmbedUnimplementedAbsServer()
}

func RegisterAbsServer(s grpc.ServiceRegistrar, srv AbsServer) {
	s.RegisterService(&Abs_ServiceDesc, srv)
}

func _Abs_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Abs_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsServer).List(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Abs_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Abs_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsServer).Create(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Abs_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Abs_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsServer).Get(ctx, req.(*EntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Abs_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Abs_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsServer).Update(ctx, req.(*EntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Abs_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AbsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Abs_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AbsServer).Delete(ctx, req.(*EntityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Abs_ServiceDesc is the grpc.ServiceDesc for Abs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Abs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.service.abs.Abs",
	HandlerType: (*AbsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Abs_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Abs_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Abs_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Abs_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Abs_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/abs/protobuf/abs.proto",
}
