// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.17.3
// source: services/email/protobuf/email.proto

package protobuf

import (
	context "context"
	protobuf "github.com/reversTeam/go-ms-tools/services/abs/protobuf"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Email_List_FullMethodName   = "/go.micro.service.email.Email/List"
	Email_Create_FullMethodName = "/go.micro.service.email.Email/Create"
	Email_Get_FullMethodName    = "/go.micro.service.email.Email/Get"
	Email_Update_FullMethodName = "/go.micro.service.email.Email/Update"
	Email_Delete_FullMethodName = "/go.micro.service.email.Email/Delete"
)

// EmailClient is the client API for Email service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailClient interface {
	List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Email_ListClient, error)
	Create(ctx context.Context, in *EmailCreateParams, opts ...grpc.CallOption) (*EmailResponse, error)
	Get(ctx context.Context, in *EmailEntity, opts ...grpc.CallOption) (*EmailResponse, error)
	Update(ctx context.Context, in *EmailUpdateParams, opts ...grpc.CallOption) (*protobuf.Response, error)
	Delete(ctx context.Context, in *EmailEntity, opts ...grpc.CallOption) (*protobuf.Response, error)
}

type emailClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailClient(cc grpc.ClientConnInterface) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) List(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (Email_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &Email_ServiceDesc.Streams[0], Email_List_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &emailListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Email_ListClient interface {
	Recv() (*EmailResponse, error)
	grpc.ClientStream
}

type emailListClient struct {
	grpc.ClientStream
}

func (x *emailListClient) Recv() (*EmailResponse, error) {
	m := new(EmailResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *emailClient) Create(ctx context.Context, in *EmailCreateParams, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, Email_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) Get(ctx context.Context, in *EmailEntity, opts ...grpc.CallOption) (*EmailResponse, error) {
	out := new(EmailResponse)
	err := c.cc.Invoke(ctx, Email_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) Update(ctx context.Context, in *EmailUpdateParams, opts ...grpc.CallOption) (*protobuf.Response, error) {
	out := new(protobuf.Response)
	err := c.cc.Invoke(ctx, Email_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailClient) Delete(ctx context.Context, in *EmailEntity, opts ...grpc.CallOption) (*protobuf.Response, error) {
	out := new(protobuf.Response)
	err := c.cc.Invoke(ctx, Email_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServer is the server API for Email service.
// All implementations must embed UnimplementedEmailServer
// for forward compatibility
type EmailServer interface {
	List(*emptypb.Empty, Email_ListServer) error
	Create(context.Context, *EmailCreateParams) (*EmailResponse, error)
	Get(context.Context, *EmailEntity) (*EmailResponse, error)
	Update(context.Context, *EmailUpdateParams) (*protobuf.Response, error)
	Delete(context.Context, *EmailEntity) (*protobuf.Response, error)
	mustEmbedUnimplementedEmailServer()
}

// UnimplementedEmailServer must be embedded to have forward compatible implementations.
type UnimplementedEmailServer struct {
}

func (UnimplementedEmailServer) List(*emptypb.Empty, Email_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedEmailServer) Create(context.Context, *EmailCreateParams) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEmailServer) Get(context.Context, *EmailEntity) (*EmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEmailServer) Update(context.Context, *EmailUpdateParams) (*protobuf.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedEmailServer) Delete(context.Context, *EmailEntity) (*protobuf.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedEmailServer) mustEmbedUnimplementedEmailServer() {}

// UnsafeEmailServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailServer will
// result in compilation errors.
type UnsafeEmailServer interface {
	mustEmbedUnimplementedEmailServer()
}

func RegisterEmailServer(s grpc.ServiceRegistrar, srv EmailServer) {
	s.RegisterService(&Email_ServiceDesc, srv)
}

func _Email_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmailServer).List(m, &emailListServer{stream})
}

type Email_ListServer interface {
	Send(*EmailResponse) error
	grpc.ServerStream
}

type emailListServer struct {
	grpc.ServerStream
}

func (x *emailListServer) Send(m *EmailResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Email_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailCreateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).Create(ctx, req.(*EmailCreateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailEntity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).Get(ctx, req.(*EmailEntity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).Update(ctx, req.(*EmailUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Email_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailEntity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Email_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServer).Delete(ctx, req.(*EmailEntity))
	}
	return interceptor(ctx, in, info, handler)
}

// Email_ServiceDesc is the grpc.ServiceDesc for Email service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Email_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.service.email.Email",
	HandlerType: (*EmailServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Email_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Email_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Email_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Email_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Email_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/email/protobuf/email.proto",
}
